package com.bob.mta.modules.plan.domain;

public enum PlanActivityType {
    PLAN_CREATED,
    PLAN_PUBLISHED,
    PLAN_UPDATED,
    PLAN_CANCELLED,
    PLAN_COMPLETED,
    PLAN_HANDOVER,
    NODE_STARTED,
    NODE_COMPLETED,
    NODE_HANDOVER,
    NODE_AUTO_COMPLETED,
    NODE_SKIPPED,
    REMINDER_POLICY_UPDATED
}
