spring:
  application:
    name: bob-mta-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/bobmta
    username: bobmta
    password: change-me
    driver-class-name: org.postgresql.Driver
  transaction:
    default-timeout: 30s
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  messages:
    basename: i18n/messages
    encoding: UTF-8
  mvc:
    format:
      date-time: yyyy-MM-dd'T'HH:mm:ssXXX
  sql:
    init:
      platform: postgresql
      mode: never
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
mybatis:
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info
jwt:
  issuer: bob-mta
  access-token:
    secret: change-me-please
    expiration-minutes: 120
logging:
  level:
    root: INFO
    com.bob.mta: DEBUG
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd''T''HH:mm:ss.SSSZ}","level":"%p","logger":"%c{1}","thread":"%t","message":%msg,"trace":%ex}'
app:
  file:
    storage: IN_MEMORY
    minio:
      endpoint: http://localhost:9000
      access-key: minioadmin
      secret-key: minioadmin
      download-expiry-seconds: 900
